### ISSUE TITLE
Pressing right repeatedly works half the time

### ISSUE THREAD

**Issue by quimnuss** [diegoquintanav/go-joystick#15]
Lowering the interval rate makes it much better for the jump (#12) but it still doesn't solve it for left and right, which makes it very hard to clear level 4 because you can't do small steps since depending on where you fall on the frontend polling interval it makes big or small steps or doesn't move at all if one presses and releases the button within the 20ms window.

I think it won't be responsive enough for a platformer if we don't switch from fixed interval polling to events as suggested in #13. The network latency will be problematic enough than to add a [0,20ms] latency on the frontend i think.

What are our options?

**Comment by quimnuss** [comment]
Mmh, lowering the sensitivity to 5 ms still has this issue. Unsure why...

**Comment by diegoquintanav** [comment]
nota mental: check level 4

**Comment by diegoquintanav** [comment]
closed by #16
