### ISSUE TITLE
User names are not within the possible names

### ISSUE THREAD

**Issue by quimnuss** [diegoquintanav/go-joystick#5]
The list of names are placeholders at the moment

you can find the list of names here: https://github.com/quimnuss/sompics/blob/main/scripts/persistence.gd

**Comment by diegoquintanav** [comment]
this is changed in https://github.com/diegoquintanav/go-joystick/blob/d80c553ab0f2e5f7bbf2e5827dfe2a4329e59ed2/cmd/joystick-client/static/js/joystick.js#L116-L124

**Comment by diegoquintanav** [comment]
@quimnuss should we load this list dynamically from some external resource? what is the final list?

**Comment by quimnuss** [comment]
Heeey, sorry the list got slightly bigger!
https://github.com/quimnuss/sompics/blob/main/scripts/persistence.gd
didn't realize there was people missing
